default_stages: ['commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  - repo: https://github.com/NixOS/nixfmt
    rev: master
    hooks:
      - id: nixfmt

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/bwhmather/ssort
    rev: 0.13.0
    hooks:
      - id: ssort

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
        args: [--py39-plus]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: python
        entry: ruff check --force-exclude
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        language: python
        entry: ruff format --force-exclude
        types_or: [python, pyi, jupyter]
        require_serial: true

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
      - id: xenon
        args: ["--max-average=A", "--max-modules=C", "--max-absolute=C", "."]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        exclude: ^tests/

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
